In [3]:
import os
import json
import pandas as pd

In [4]:
import mysql.connector as sql

my_db = sql.connect(
    host="localhost",
    user="root",
    password="12345678",
     database="phonepay_pulse"
)

cursor = my_db.cursor()
mycursor = my_db.cursor(buffered=True)

# Create database
cursor.execute("CREATE DATABASE IF NOT EXISTS phonepay_pulse")

print("Database created successfully!")

Database created successfully!

In [11]:

# -------------------- CREATE TABLE --------------------
mycursor.execute("""
CREATE TABLE IF NOT EXISTS aggregated_transaction (
    State VARCHAR(255),
    Year INT,
    Quarter INT,
    Transaction_type VARCHAR(255),
    Transaction_count BIGINT,
    Transaction_amount DOUBLE
)
""")

print("Table created ")

# -------------------- PATH --------------------
path = r"D:\Guvi\Mini-project _1_(Python+SQL)\phonepay_pulse\pulse\data\aggregated\transaction\country\india\state\\"

# -------------------- DATA EXTRACTION --------------------
data_list = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            file_path = os.path.join(year_path, file)

            with open(file_path, 'r') as f:
                data = json.load(f)

                # check if data exists
                if data.get('data') and data['data'].get('transactionData'):
                    for item in data['data']['transactionData']:
                        data_list.append((
                            state,
                            int(year),
                            int(file.strip(".json")),
                            item['name'],
                            item['paymentInstruments'][0]['count'],
                            item['paymentInstruments'][0]['amount']
                        ))

print("Data extracted ")

# -------------------- INSERT INTO MYSQL --------------------
query = """
INSERT INTO aggregated_transaction
(State, Year, Quarter, Transaction_type, Transaction_count, Transaction_amount)
VALUES (%s, %s, %s, %s, %s, %s)
"""

mycursor.executemany(query, data_list)
my_db.commit()

print("Data inserted successfully ")

Table created
Data extracted
Data inserted successfully

In [12]:


# -------------------- MYSQL CONNECTION --------------------
my_db = sql.connect(
    host="localhost",
    user="root",
    password="12345678",
    database="phonepay_pulse"
)

mycursor = my_db.cursor()

# -------------------- CREATE TABLE --------------------
mycursor.execute("""
CREATE TABLE IF NOT EXISTS aggregated_users (
    State VARCHAR(255),
    Year INT,
    Quarter INT,
    User_brand VARCHAR(255),
    User_count BIGINT,
    User_percentage FLOAT
)
""")

print("Table created ")

# -------------------- PATH --------------------
path = r"D:\Guvi\Mini-project _1_(Python+SQL)\phonepay_pulse\pulse\data\aggregated\user\country\india\state\\"

# -------------------- DATA EXTRACTION --------------------
data_list = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            file_path = os.path.join(year_path, file)

            with open(file_path, 'r') as f:
                data = json.load(f)

                # some files may not have usersByDevice
                if data.get('data') and data['data'].get('usersByDevice'):
                    for item in data['data']['usersByDevice']:
                        data_list.append((
                            state,
                            int(year),
                            int(file.strip(".json")),
                            item['brand'],
                            item['count'],
                            item['percentage'] * 100
                        ))

print("Data extracted ")

# -------------------- INSERT INTO MYSQL --------------------
query = """
INSERT INTO aggregated_users
(State, Year, Quarter, User_brand, User_count, User_percentage)
VALUES (%s, %s, %s, %s, %s, %s)
"""

mycursor.executemany(query, data_list)
my_db.commit()

print("Data inserted successfully ")

Table created
Data extracted
Data inserted successfully

In [ ]:



# -------------------- MYSQL CONNECTION --------------------
my_db = sql.connect(
    host="localhost",
    user="root",
    password="12345678",
    database="phonepay_pulse"
)

mycursor = my_db.cursor()

# -------------------- CREATE TABLE --------------------
mycursor.execute("""
CREATE TABLE IF NOT EXISTS map_transaction (
    State VARCHAR(255),
    Year INT,
    Quarter INT,
    District VARCHAR(255),
    Transaction_count BIGINT,
    Transaction_amount DOUBLE
)
""")

print("Table created ")

# -------------------- PATH --------------------
path = r"D:\Guvi\Mini-project _1_(Python+SQL)\phonepay_pulse\pulse\data\map\transaction\hover\country\india\state\\"

# -------------------- DATA EXTRACTION --------------------
data_list = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            file_path = os.path.join(year_path, file)

            with open(file_path, 'r') as f:
                data = json.load(f)

                if data.get('data') and data['data'].get('hoverDataList'):
                    for item in data['data']['hoverDataList']:
                        district = item['name'].replace(" district", "")

                        data_list.append((
                            state,
                            int(year),
                            int(file.strip(".json")),
                            district,
                            item['metric'][0]['count'],
                            item['metric'][0]['amount']
                        ))

print("Data extracted ")

# -------------------- INSERT INTO MYSQL --------------------
query = """
INSERT INTO map_transaction
(State, Year, Quarter, District, Transaction_count, Transaction_amount)
VALUES (%s, %s, %s, %s, %s, %s)
"""

mycursor.executemany(query, data_list)
my_db.commit()

print("Data inserted successfully ")

Table created
Data extracted
Data inserted successfully

In [ ]:


# -------------------- MYSQL CONNECTION --------------------
my_db = sql.connect(
    host="localhost",
    user="root",
    password="12345678",
    database="phonepay_pulse"
)

mycursor = my_db.cursor()

# -------------------- CREATE TABLE --------------------
mycursor.execute("""
CREATE TABLE IF NOT EXISTS map_users (
    State VARCHAR(255),
    Year INT,
    Quarter INT,
    District VARCHAR(255),
    Registered_user BIGINT,
    App_opens BIGINT
)
""")

print("Table created ")

# -------------------- PATH --------------------
path = r"D:\Guvi\Mini-project _1_(Python+SQL)\phonepay_pulse\pulse\data\map\user\hover\country\india\state\\"

# -------------------- DATA EXTRACTION --------------------
data_list = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            file_path = os.path.join(year_path, file)

            with open(file_path, 'r') as f:
                data = json.load(f)

                if data.get('data') and data['data'].get('hoverData'):
                    for district, values in data['data']['hoverData'].items():

                        data_list.append((
                            state,
                            int(year),
                            int(file.strip(".json")),
                            district.replace(" district", ""),
                            values.get('registeredUsers', 0),
                            values.get('appOpens', 0)
                        ))

print("Data extracted ")

# -------------------- INSERT INTO MYSQL --------------------
query = """
INSERT INTO map_users
(State, Year, Quarter, District, Registered_user, App_opens)
VALUES (%s, %s, %s, %s, %s, %s)
"""

mycursor.executemany(query, data_list)
my_db.commit()

print("Data inserted successfully ")

Table created
Data extracted
Data inserted successfully

In [ ]:


# -------------------- MYSQL CONNECTION --------------------
my_db = sql.connect(
    host="localhost",
    user="root",
    password="12345678",
    database="phonepay_pulse"
)

mycursor = my_db.cursor()

# -------------------- CREATE TABLE --------------------
mycursor.execute("""
CREATE TABLE IF NOT EXISTS top_transaction_district (
    State VARCHAR(255),
    Year INT,
    Quarter INT,
    District VARCHAR(255),
    Transaction_count BIGINT,
    Transaction_amount DOUBLE
)
""")

print("Table created ")

# -------------------- PATH --------------------
path = r"D:\Guvi\Mini-project _1_(Python+SQL)\phonepay_pulse\pulse\data\top\transaction\country\india\state\\"

# -------------------- DATA EXTRACTION --------------------
data_list = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            file_path = os.path.join(year_path, file)

            with open(file_path, 'r') as f:
                data = json.load(f)

                if data.get('data') and data['data'].get('districts'):
                    for item in data['data']['districts']:

                        data_list.append((
                            state,
                            int(year),
                            int(file.strip(".json")),
                            item['entityName'],
                            item['metric']['count'],
                            item['metric']['amount']
                        ))

print("Data extracted ")

# -------------------- INSERT INTO MYSQL --------------------
query = """
INSERT INTO top_transaction_district
(State, Year, Quarter, District, Transaction_count, Transaction_amount)
VALUES (%s, %s, %s, %s, %s, %s)
"""

mycursor.executemany(query, data_list)
my_db.commit()

print("Data inserted successfully ")

Table created
Data extracted
Data inserted successfully

In [ ]:


# -------------------- MYSQL CONNECTION --------------------
my_db = sql.connect(
    host="localhost",
    user="root",
    password="12345678",
    database="phonepay_pulse"
)

mycursor = my_db.cursor()

# -------------------- CREATE TABLE --------------------
mycursor.execute("""
CREATE TABLE IF NOT EXISTS top_transaction_pincode (
    State VARCHAR(255),
    Year INT,
    Quarter INT,
    Pincode INT,
    Transaction_count BIGINT,
    Transaction_amount DOUBLE
)
""")

print("Table created ")

# -------------------- PATH --------------------
path = r"D:\Guvi\Mini-project _1_(Python+SQL)\phonepay_pulse\pulse\data\top\transaction\country\india\state\\"

# -------------------- DATA EXTRACTION --------------------
data_list = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            file_path = os.path.join(year_path, file)

            with open(file_path, 'r') as f:
                data = json.load(f)

                if data.get('data') and data['data'].get('pincodes'):
                    for item in data['data']['pincodes']:

                        data_list.append((
                            state,
                            int(year),
                            int(file.strip(".json")),
                            int(item['entityName'])if item['entityName'] else None,
                            item['metric']['count'],
                            item['metric']['amount']
                        ))

print("Data extracted ")

# -------------------- INSERT INTO MYSQL --------------------
query = """
INSERT INTO top_transaction_pincode
(State, Year, Quarter, Pincode, Transaction_count, Transaction_amount)
VALUES (%s, %s, %s, %s, %s, %s)
"""

mycursor.executemany(query, data_list)
my_db.commit()

print("Data inserted successfully ")

Table created
Data extracted
Data inserted successfully

In [ ]:


# -------------------- MYSQL CONNECTION --------------------
my_db = sql.connect(
    host="localhost",
    user="root",
    password="12345678",
    database="phonepay_pulse"
)

mycursor = my_db.cursor()

# -------------------- CREATE TABLE --------------------
mycursor.execute("""
CREATE TABLE IF NOT EXISTS top_users_district (
    State VARCHAR(255),
    Year INT,
    Quarter INT,
    District VARCHAR(255),
    Registered_user BIGINT
)
""")

print("Table created ")

# -------------------- PATH --------------------
path = r"D:\Guvi\Mini-project _1_(Python+SQL)\phonepay_pulse\pulse\data\top\user\country\india\state\\"

# -------------------- DATA EXTRACTION --------------------
data_list = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            file_path = os.path.join(year_path, file)

            with open(file_path, 'r') as f:
                data = json.load(f)

                if data.get('data') and data['data'].get('districts'):
                    for item in data['data']['districts']:

                        data_list.append((
                            state,
                            int(year),
                            int(file.strip(".json")),
                            item['name'],
                            item['registeredUsers']
                        ))

print("Data extracted ")

# -------------------- INSERT INTO MYSQL --------------------
query = """
INSERT INTO top_users_district
(State, Year, Quarter, District, Registered_user)
VALUES (%s, %s, %s, %s, %s)
"""

mycursor.executemany(query, data_list)
my_db.commit()

print("Data inserted successfully ")

Table created
Data extracted
Data inserted successfully

In [ ]:

# -------------------- MYSQL CONNECTION --------------------
my_db = sql.connect(
    host="localhost",
    user="root",
    password="12345678",
    database="phonepay_pulse"
)

mycursor = my_db.cursor()

# -------------------- CREATE TABLE --------------------
mycursor.execute("""
CREATE TABLE IF NOT EXISTS top_users_pincode (
    State VARCHAR(255),
    Year INT,
    Quarter INT,
    Pincode INT,
    Registered_user BIGINT
)
""")

print("Table created ")

# -------------------- PATH --------------------
path = r"D:\Guvi\Mini-project _1_(Python+SQL)\phonepay_pulse\pulse\data\top\user\country\india\state\\"

# -------------------- DATA EXTRACTION --------------------
data_list = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            file_path = os.path.join(year_path, file)

            with open(file_path, 'r') as f:
                data = json.load(f)

                if data.get('data') and data['data'].get('pincodes'):
                    for item in data['data']['pincodes']:

                        data_list.append((
                            state,
                            int(year),
                            int(file.strip(".json")),
                            int(item['name']) if item['name'] else None,
                            item['registeredUsers']
                        ))

print("Data extracted ")

# -------------------- INSERT INTO MYSQL --------------------
query = """
INSERT INTO top_users_pincode
(State, Year, Quarter, Pincode, Registered_user)
VALUES (%s, %s, %s, %s, %s)
"""

mycursor.executemany(query, data_list)
my_db.commit()

print("Data inserted successfully ")

Table created
Data extracted
Data inserted successfully

In [ ]:


# -------------------- MYSQL CONNECTION --------------------
my_db = sql.connect(
    host="localhost",
    user="root",
    password="12345678",
    database="phonepay_pulse"
)

mycursor = my_db.cursor()

# -------------------- CREATE TABLE --------------------
mycursor.execute("""
CREATE TABLE IF NOT EXISTS aggregated_insurance (
    State VARCHAR(255),
    Year INT,
    Quarter INT,
    Insurance_type VARCHAR(255),
    Insurance_count BIGINT,
    Insurance_amount DOUBLE
)
""")

print("Table created ")

# -------------------- PATH --------------------
path = r"D:\Guvi\Mini-project _1_(Python+SQL)\phonepay_pulse\pulse\data\aggregated\insurance\country\india\state\\"

# -------------------- DATA EXTRACTION --------------------
data_list = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            file_path = os.path.join(year_path, file)

            with open(file_path, 'r') as f:
                data = json.load(f)

                if data.get('data') and data['data'].get('transactionData'):
                    for item in data['data']['transactionData']:
                        data_list.append((
                            state,
                            int(year),
                            int(file.strip(".json")),
                            item['name'],
                            item['paymentInstruments'][0]['count'],
                            item['paymentInstruments'][0]['amount']
                        ))

print("Data extracted ")

# -------------------- INSERT INTO MYSQL --------------------
query = """
INSERT INTO aggregated_insurance
(State, Year, Quarter, Insurance_type, Insurance_count, Insurance_amount)
VALUES (%s, %s, %s, %s, %s, %s)
"""

mycursor.executemany(query, data_list)
my_db.commit()

print("Data inserted successfully ")

Table created
Data extracted
Data inserted successfully

In [ ]:


# -------------------- MYSQL CONNECTION --------------------
my_db = sql.connect(
    host="localhost",
    user="root",
    password="12345678",
    database="phonepay_pulse"
)

mycursor = my_db.cursor()

# -------------------- CREATE TABLE --------------------
mycursor.execute("""
CREATE TABLE IF NOT EXISTS map_insurance (
    State VARCHAR(255),
    Year INT,
    Quarter INT,
    District VARCHAR(255),
    Insurance_count BIGINT,
    Insurance_amount DOUBLE
)
""")

print("Table created ")

# -------------------- PATH --------------------
path = r"D:\Guvi\Mini-project _1_(Python+SQL)\phonepay_pulse\pulse\data\map\insurance\hover\country\india\state\\"

# -------------------- DATA EXTRACTION --------------------
data_list = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            file_path = os.path.join(year_path, file)

            with open(file_path, 'r') as f:
                data = json.load(f)

                if data.get('data') and data['data'].get('hoverDataList'):
                    for item in data['data']['hoverDataList']:

                        data_list.append((
                            state,
                            int(year),
                            int(file.strip(".json")),
                            item['name'].replace(" district", ""),
                            item['metric'][0]['count'],
                            item['metric'][0]['amount']
                        ))

print("Data extracted ")

# -------------------- INSERT INTO MYSQL --------------------
query = """
INSERT INTO map_insurance
(State, Year, Quarter, District, Insurance_count, Insurance_amount)
VALUES (%s, %s, %s, %s, %s, %s)
"""

mycursor.executemany(query, data_list)
my_db.commit()

print("Data inserted successfully ")

Table created
Data extracted
Data inserted successfully

In [ ]:


# -------------------- MYSQL CONNECTION --------------------
my_db = sql.connect(
    host="localhost",
    user="root",
    password="12345678",
    database="phonepay_pulse"
)

mycursor = my_db.cursor()

# -------------------- CREATE TABLE --------------------
mycursor.execute("""
CREATE TABLE IF NOT EXISTS top_insurance_district (
    State VARCHAR(255),
    Year INT,
    Quarter INT,
    District VARCHAR(255),
    Insurance_count BIGINT,
    Insurance_amount DOUBLE
)
""")

print("Table created ")

# -------------------- PATH --------------------
path = r"D:\Guvi\Mini-project _1_(Python+SQL)\phonepay_pulse\pulse\data\top\insurance\country\india\state\\"

# -------------------- DATA EXTRACTION --------------------
data_list = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            file_path = os.path.join(year_path, file)

            with open(file_path, 'r') as f:
                data = json.load(f)

                if data.get('data') and data['data'].get('districts'):
                    for item in data['data']['districts']:

                        data_list.append((
                            state,
                            int(year),
                            int(file.strip(".json")),
                            item['entityName'],
                            item['metric']['count'],
                            item['metric']['amount']
                        ))

print("Data extracted ")

# -------------------- INSERT INTO MYSQL --------------------
query = """
INSERT INTO top_insurance_district
(State, Year, Quarter, District, Insurance_count, Insurance_amount)
VALUES (%s, %s, %s, %s, %s, %s)
"""

mycursor.executemany(query, data_list)
my_db.commit()

print("Data inserted successfully ")

Table created
Data extracted
Data inserted successfully

In [7]:


# -------------------- MYSQL CONNECTION --------------------
my_db = sql.connect(
    host="localhost",
    user="root",
    password="12345678",
    database="phonepay_pulse"
)

mycursor = my_db.cursor()

# -------------------- CREATE TABLE --------------------
mycursor.execute("""
CREATE TABLE IF NOT EXISTS top_insurance_pincode (
    State VARCHAR(255),
    Year INT,
    Quarter INT,
    Pincode INT,
    Insurance_count BIGINT,
    Insurance_amount DOUBLE
)
""")

print("Table created ")

# -------------------- PATH --------------------
path = r"D:\Guvi\Mini-project _1_(Python+SQL)\phonepay_pulse\pulse\data\top\insurance\country\india\state\\"

# -------------------- DATA EXTRACTION --------------------
data_list = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            file_path = os.path.join(year_path, file)

            with open(file_path, 'r') as f:
                data = json.load(f)

                if data.get('data') and data['data'].get('pincodes'):
                    for item in data['data']['pincodes']:

                        data_list.append((
                            state,
                            int(year),
                            int(file.strip(".json")),
                            int(item['entityName']) if item['entityName'] else None,
                            item['metric']['count'],
                            item['metric']['amount']
                        ))

print("Data extracted ")

# -------------------- INSERT INTO MYSQL --------------------
query = """
INSERT INTO top_insurance_pincode
(State, Year, Quarter, Pincode, Insurance_count, Insurance_amount)
VALUES (%s, %s, %s, %s, %s, %s)
"""

mycursor.executemany(query, data_list)
my_db.commit()

print("Data inserted successfully ")

Table created
Data extracted
Data inserted successfully

# 1. Decoding Transaction Dynamics on PhonePe

#   Query:1.Total Transactions Over Years

In [30]:
query = '''SELECT Year,
       SUM(Transaction_count) AS Total_Transactions
FROM aggregated_transaction
GROUP BY Year
ORDER BY Year'''

cursor.execute(query)

result = cursor.fetchall()

# Convert to DataFrame
df = pd.DataFrame(result, columns=[
    "Year",
    "Total_Transactions"
])

print(df)

   Year Total_Transactions
0  2018         5401012050
1  2019        20399136075
2  2020        39869873705
3  2021        96442146100
4  2022       196506468670
5  2023       321285273435
6  2024       496517174335

In [31]:
import plotly.express as px
fig = px.line(
    df,
    x="Year",
    y="Total_Transactions",
    title="Total Transactions Over Years",
    markers=True,
    line_shape="spline",             
    color_discrete_sequence=["#2E86AB"],
    width=900,
    height=500
)
fig.show()

# Query:2.Total Transaction Amount Over Years

In [92]:
query = """
SELECT Year,
SUM(Transaction_amount) AS Total_Amount
FROM aggregated_transaction
GROUP BY Year
ORDER BY Year
"""

cursor.execute(query)
data = cursor.fetchall()

df = pd.DataFrame(data, columns=["Year","Total_Amount"])
print(df)

   Year  Total_Amount
0  2018  8.115227e+12
1  2019  3.138344e+13
2  2020  7.320581e+13
3  2021  1.729935e+14
4  2022  3.213317e+14
5  2023  4.724591e+14
6  2024  6.481228e+14

In [94]:
import plotly.express as px
fig = px.line(
    df,
    x="Year",
    y="Total_Amount",
    title="Total Transaction Amount Over Years",
    markers=True,
    line_shape="spline",             
    color_discrete_sequence=["#2E86AB"],
    width=900,
    height=500
)
fig.update_traces(
    marker=dict(size=6),
    line=dict(width=2))
fig.show()

# Query:3.Top 10 States by Transaction Amount

In [7]:
query ='''SELECT State,
SUM(Transaction_amount) AS Total_Amount
FROM aggregated_transaction
GROUP BY State
ORDER BY Total_Amount DESC
LIMIT 10''' 

cursor.execute(query)
result = cursor.fetchall()

df = pd.DataFrame(result,columns=[
                  "State",
                  "Total_Amount"])
print(df)

            State  Total_Amount
0       telangana  2.082798e+14
1       karnataka  2.033936e+14
2     maharashtra  2.018710e+14
3  andhra-pradesh  1.733454e+14
4   uttar-pradesh  1.344261e+14
5       rajasthan  1.317162e+14
6  madhya-pradesh  9.562640e+13
7           bihar  8.950675e+13
8     west-bengal  7.792082e+13
9          odisha  6.131991e+13

In [24]:
import plotly.express as px
colors = [
    "#636EFA",  # blue
    "#EF553B",  # red
    "#00CC96",  # green
    "#AB63FA",  # purple
    "#FFA15A",  # orange
    "#19D3F3",  # cyan
    "#FF6692",  # pink
    "#B6E880",  # light green
    "#FF97FF"   # magenta
]
fig = px.bar(
    df,
    x="State",
    y="Total_Amount",
    color= "State",
    title="Top 10 States by Transaction Amount",
    color_discrete_sequence= colors
)

fig.update_layout(
    title_x=0.5,
    template="plotly_white",
    width=1000,
    height=500,
    bargap=0.2,
    xaxis_tickangle=-45
)

fig.show()

# Query:4.Transaction Type Distribution

In [33]:
query = """
SELECT Transaction_type,
SUM(Transaction_count) AS Total_Transactions
FROM aggregated_transaction
GROUP BY Transaction_type
ORDER BY Total_Transactions DESC
"""

cursor.execute(query)
data = cursor.fetchall()

df = pd.DataFrame(data, columns=["Transaction_type","Total_Transactions"])
print(df)

           Transaction_type Total_Transactions
0         Merchant payments       651193777435
1     Peer-to-peer payments       425162233265
2  Recharge & bill payments        97983778015
3                    Others         1310250940
4        Financial Services          771044715

In [34]:
import plotly.express as px
fig = px.pie(
    df,
    names="Transaction_type",
    values="Total_Transactions",
    title="Transaction Type Distribution",
    hole=0.4,
    width=900,
    height=500
)

fig.show()

# Query:5.Top states transaction trend

In [36]:
query = """
SELECT State, Year,
SUM(Transaction_amount) AS Total_Amount
FROM aggregated_transaction
GROUP BY State, Year
ORDER BY State, Year
"""

cursor.execute(query)
data = cursor.fetchall()

import pandas as pd

df = pd.DataFrame(data, columns=["State","Year","Total_Amount"])

print(df["State"].unique())

<StringArray>
[         'andaman-&-nicobar-islands',                     'andhra-pradesh',
                  'arunachal-pradesh',                              'assam',
                              'bihar',                         'chandigarh',
                       'chhattisgarh', 'dadra-&-nagar-haveli-&-daman-&-diu',
                              'delhi',                                'goa',
                            'gujarat',                            'haryana',
                   'himachal-pradesh',                    'jammu-&-kashmir',
                          'jharkhand',                          'karnataka',
                             'kerala',                             'ladakh',
                        'lakshadweep',                     'madhya-pradesh',
                        'maharashtra',                            'manipur',
                          'meghalaya',                            'mizoram',
                           'nagaland',                             'odisha',
                         'puducherry',                             'punjab',
                          'rajasthan',                             'sikkim',
                         'tamil-nadu',                          'telangana',
                            'tripura',                      'uttar-pradesh',
                        'uttarakhand',                        'west-bengal']
Length: 36, dtype: str

In [37]:
top_states = df.groupby("State")["Total_Amount"].sum()

top_states = top_states.sort_values(ascending=False).head(5)

top_states_list = list(top_states.index)

print(top_states_list)

['telangana', 'karnataka', 'maharashtra', 'andhra-pradesh', 'uttar-pradesh']

In [38]:
df_top = df[df["State"].isin(top_states_list)]

print(df_top["State"].unique())

<StringArray>
['andhra-pradesh', 'karnataka', 'maharashtra', 'telangana', 'uttar-pradesh']
Length: 5, dtype: str

In [39]:
fig = px.line(
    df_top,
    x="Year",
    y="Total_Amount",
    color="State",
    markers=True,
    title="Top 5 States Transaction Trend",
    width=900,
    height=500
)

fig.show()

# 2. Device Dominance and User Engagement Analysis

#  Query 1 — Top Device Brands by Registered Users

In [40]:
query = """
SELECT User_brand,
SUM(User_count) AS Total_Users
FROM aggregated_users
GROUP BY User_brand
ORDER BY Total_Users DESC
LIMIT 10
"""

cursor.execute(query)
data = cursor.fetchall()

import pandas as pd

df = pd.DataFrame(data, columns=["Brand","Total_Users"])

print(df)

      Brand Total_Users
0    Xiaomi  3478250468
1   Samsung  2686414844
2      Vivo  2501660076
3      Oppo  1681000980
4    Others  1131800936
5    Realme   879892888
6     Apple   383789256
7  Motorola   293362936
8   OnePlus   254708844
9    Huawei   228518772

In [41]:
import plotly.express as px

fig = px.bar(
    df,
    x="Brand",
    y="Total_Users",
    title="Top Device Brands by Registered Users",
    color="Brand",
    width=900,
    height= 500
)

fig.show()

# Query-2:Device Brands by User Percentage

In [42]:
query = """
SELECT User_brand,
AVG(User_percentage) AS Avg_User_Percentage
FROM aggregated_users
GROUP BY User_brand
ORDER BY Avg_User_Percentage DESC
LIMIT 10
"""

cursor.execute(query)
data = cursor.fetchall()

import pandas as pd
df = pd.DataFrame(data, columns=["Brand","Avg_Percentage"])

print(df)

      Brand  Avg_Percentage
0    Xiaomi       26.133786
1   Samsung       19.208622
2      Vivo       16.599633
3      Oppo       11.596724
4    Others        9.100424
5    Realme        5.896628
6     Apple        3.353331
7  Micromax        2.449635
8   OnePlus        2.360884
9  Motorola        2.173314

In [43]:
import plotly.express as px

fig = px.pie(
    df,
    names="Brand",
    values="Avg_Percentage",
    title="Device Brand Market Share",
    width=900,
    height=500
)

fig.show()

# Query:3.Device Brand Usage Growth Over Year

In [89]:
query = """
SELECT Year,
User_brand,
SUM(User_count) AS Total_Users
FROM aggregated_users
GROUP BY Year, User_brand
ORDER BY Year
"""

cursor.execute(query)
data = cursor.fetchall()

import pandas as pd

df = pd.DataFrame(data, columns=["Year","Brand","Total_Users"])
df["Year"] = df["Year"].astype(int)

df

    Year    Brand Total_Users
0   2018    Apple    39887192
1   2018     Asus     1721568
2   2018  COOLPAD          40
3   2018   Gionee     2893248
4   2018   Huawei    17150584
..   ...      ...         ...
82  2022   Realme   130741856
83  2022  Samsung   263546200
84  2022    Tecno    14630404
85  2022     Vivo   308897540
86  2022   Xiaomi   353706668

[87 rows x 3 columns]

In [91]:
import plotly.express as px

fig = px.line(
    df,
    x="Year",
    y="Total_Users",
    color="Brand",
    markers=True,
    title="Device Brand Usage Growth Over Years",
    width=900,
    height=500
)
fig.update_traces(
    marker=dict(size=5),
    line=dict(width=2))
fig.update_xaxes(type='category') 
fig.show()

# Query:4.Top Device Brand in Each State

In [48]:
query = """
SELECT State,
       User_brand,
       SUM(User_count) AS Total_Users
FROM aggregated_users
WHERE User_brand != 'Others'
GROUP BY State, User_brand
ORDER BY State, Total_Users DESC
"""
cursor.execute(query)
data = cursor.fetchall()
import pandas as pd

df = pd.DataFrame(data, columns=["State","Brand","Total_Users"])
df_top = df.sort_values("Total_Users", ascending=False).drop_duplicates("State")
print(df_top)

                                  State    Brand Total_Users
238                         maharashtra   Xiaomi   451471756
396                       uttar-pradesh   Xiaomi   364104124
183                           karnataka   Xiaomi   297983348
11                       andhra-pradesh   Xiaomi   226319504
372                           telangana   Xiaomi   219160800
424                         west-bengal   Xiaomi   216661784
336                           rajasthan     Vivo   197844240
47                                bihar   Xiaomi   191401100
226                      madhya-pradesh   Xiaomi   185034532
362                          tamil-nadu   Xiaomi   182799108
120                             gujarat     Vivo   164676488
98                                delhi   Xiaomi   132782644
302                              odisha   Xiaomi   128950296
131                             haryana   Xiaomi   117284472
193                              kerala   Xiaomi    72875876
168                           jharkhand   Xiaomi    72746188
323                              punjab   Xiaomi    62806628
72                         chhattisgarh   Xiaomi    49933780
33                                assam   Xiaomi    40368184
410                         uttarakhand   Xiaomi    31314072
142                    himachal-pradesh   Xiaomi    22911708
156                     jammu-&-kashmir   Xiaomi    19981648
109                                 goa   Xiaomi     6903688
249                             manipur   Xiaomi     6509000
382                             tripura   Xiaomi     5273712
60                           chandigarh   Xiaomi     4941912
313                          puducherry   Xiaomi     3688532
85   dadra-&-nagar-haveli-&-daman-&-diu     Vivo     3677144
289                            nagaland   Xiaomi     2737708
21                    arunachal-pradesh   Xiaomi     2610256
348                              sikkim  Samsung     2343632
263                           meghalaya   Xiaomi     2074060
277                             mizoram   Xiaomi     1174828
203                              ladakh   Xiaomi      949292
0             andaman-&-nicobar-islands   Xiaomi      595008
214                         lakshadweep     Vivo       43904

In [49]:
df_top = df_top.sort_values("Total_Users", ascending=True)

In [53]:
import plotly.express as px

fig = px.bar(
    df_top,
    y="State",
    x="Total_Users",
    color="Brand",
    title="Most Popular Device Brand in Each State",
    orientation="h",
    width=900,
    height=500
)

fig.show()

# Query:5. Top 10 Device Brands Comparison

In [58]:
query = """SELECT User_brand,
SUM(User_count) AS Total_Users
FROM aggregated_users
WHERE User_brand != 'Others'
GROUP BY User_brand
ORDER BY Total_Users DESC
LIMIT 10""" 

cursor.execute(query)
data = cursor.fetchall()

df = pd.DataFrame(data, columns=["Brand","Total_Users"])
df

      Brand Total_Users
0    Xiaomi  3478250468
1   Samsung  2686414844
2      Vivo  2501660076
3      Oppo  1681000980
4    Realme   879892888
5     Apple   383789256
6  Motorola   293362936
7   OnePlus   254708844
8    Huawei   228518772
9    Lenovo   170258192

In [59]:
import plotly.express as px

fig = px.bar(
    df,
    x="Brand",
    y="Total_Users",
    title="Top Device Brands by Registered Users",
    labels={"Brand": "Device Brand", "Total_Users": "Total Users"},
    text="Total_Users",
    color="Brand",
    color_discrete_sequence=px.colors.qualitative.Set3
)

fig.update_layout(
    title_x=0.5,
    template="plotly_white",
    width=900,
    height=500,
    xaxis_title="Device Brand",
    yaxis_title="Total Users",
    bargap=0.25,
    plot_bgcolor="#F8F9FA",
    paper_bgcolor="#FFFFFF",
    font=dict(size=14)
)

fig.update_traces(
    textposition="outside"
)

fig.show()

# 3. Insurance Penetration and Growth Potential Analysis

# Query:1.Insurance Growth Over Years

In [86]:
query = """ 
SELECT  
    Year,
    SUM(Insurance_count) AS Total_Policies,
    SUM(Insurance_amount) AS Total_Insurance_Value
FROM aggregated_insurance
GROUP BY Year
ORDER BY Year;
""" 
cursor.execute(query)
data = cursor.fetchall()

df = pd.DataFrame(data, columns=["Year","Total_Policies","Total_Insurance_Value"])
print(df.to_string(float_format='{:,.0f}'.format))

   Year Total_Policies  Total_Insurance_Value
0  2020        2364774            882,621,525
1  2021        4749846          4,497,510,114
2  2022        9270348         12,716,530,293
3  2023       11958561         18,169,818,174
4  2024       15203532         23,780,255,046

In [87]:
import plotly.express as px

fig = px.line(
    df,
    x="Year",
    y="Total_Policies",
    markers=True,
    title="Insurance Adoption Growth Over Years",
    line_shape="spline",             
    color_discrete_sequence=["#2E86AB"],
    width=900,
    height=500
)
fig.update_traces(
    marker=dict(size=9),
    line=dict(width=2))
fig.update_xaxes(type='category') 
fig.show()

#  Query:2.Top States by Insurance Policies

In [74]:
query = """ 
SELECT 
    State,
    SUM(Insurance_count) AS Total_Policies
FROM map_insurance
GROUP BY State
ORDER BY Total_Policies DESC
LIMIT 10
""" 
cursor.execute(query)
data = cursor.fetchall()

df = pd.DataFrame(data, columns=["State","Total_Policies"])
df

            State Total_Policies
0       karnataka        5872212
1     maharashtra        5446617
2      tamil-nadu        3645807
3   uttar-pradesh        3417459
4       telangana        2683026
5     west-bengal        2519145
6          kerala        2472705
7  andhra-pradesh        2093307
8           delhi        1957542
9       rajasthan        1919052

In [75]:
import plotly.express as px

fig = px.bar(
    df,
    x="State",
    y="Total_Policies",
    title="Top States by Insurance Adoption",
    text="Total_Policies",
    color="State",
    color_discrete_sequence=px.colors.qualitative.Bold
)

fig.update_layout(
    title_x=0.5,
    template="plotly_white",
    width=1000,
    height=600,
    bargap=0.25,
    xaxis_tickangle=-45,
    plot_bgcolor="#F8F9FA",
    paper_bgcolor="#FFFFFF"
)

fig.update_traces(textposition="outside")

fig.show()

# Query:3.Lowest insurance adoption states

In [76]:
query = """ 
SELECT 
    State,
    SUM(Insurance_count) AS Total_Policies
FROM map_insurance
GROUP BY State
ORDER BY Total_Policies asc
LIMIT 10
""" 
cursor.execute(query)
data = cursor.fetchall()

df = pd.DataFrame(data, columns=["State","Total_Policies"])
df

                                State Total_Policies
0                         lakshadweep           1488
1                              ladakh          10014
2                             mizoram          11172
3                             manipur          11193
4                            nagaland          14235
5                              sikkim          14688
6                   arunachal-pradesh          30642
7                           meghalaya          31383
8           andaman-&-nicobar-islands          38991
9  dadra-&-nagar-haveli-&-daman-&-diu          41376

In [77]:
fig = px.bar(
    df,
    x="State",
    y="Total_Policies",
    title="States with Lowest Insurance Adoption",
    text="Total_Policies",
    color="State",
    color_discrete_sequence=px.colors.qualitative.Bold
)

fig.update_layout(
    title_x=0.5,
    template="plotly_white",
    width=1000,
    height=600,
    bargap=0.25,
    xaxis_tickangle=-45,
    plot_bgcolor="#F8F9FA",
    paper_bgcolor="#FFFFFF"
)

fig.update_traces(textposition="outside")

# Query:4.Top States by Insurance Value

In [78]:
query = """ 
SELECT 
    State,
    SUM(Insurance_count) AS Total_Policies,
    SUM(Insurance_amount) AS Total_Insurance_Value
FROM map_insurance
GROUP BY State
ORDER BY Total_Insurance_Value DESC
LIMIT 10""" 

cursor.execute(query)
data = cursor.fetchall()

df = pd.DataFrame(data, columns=["State","Total_Policies","Total_Insurance_value"])
print(df.to_string(float_format='{:,.0f}'.format))

           State Total_Policies  Total_Insurance_value
0      karnataka        5872212          8,229,464,541
1    maharashtra        5446617          7,089,385,608
2  uttar-pradesh        3417459          5,221,039,485
3     tamil-nadu        3645807          4,666,521,759
4         kerala        2472705          3,941,155,521
5      telangana        2683026          3,513,178,545
6    west-bengal        2519145          3,157,389,717
7      rajasthan        1919052          2,878,961,580
8        haryana        1721214          2,492,943,681
9          delhi        1957542          2,446,095,516

In [80]:
fig = px.bar(
    df,
    x="State",
    y="Total_Insurance_value",
    title="Top States by Insurance value",
    text="Total_Insurance_value",
    color="State",
    color_discrete_sequence=px.colors.qualitative.Bold
)

fig.update_layout(
    title_x=0.5,
    template="plotly_white",
    width=1000,
    height=600,
    bargap=0.25,
    xaxis_tickangle=-45,
    plot_bgcolor="#F8F9FA",
    paper_bgcolor="#FFFFFF"
)

fig.update_traces(textposition="outside")

# Query 5 — Insurance Adoption Trend by Quarter

In [82]:
query = """ 
SELECT 
    Year,
    Quarter,
    SUM(Insurance_count) AS Total_Policies,
    SUM(Insurance_amount) AS Total_Insurance_Value
FROM aggregated_insurance
GROUP BY Year, Quarter
ORDER BY Year, Quarter""" 

cursor.execute(query)
data = cursor.fetchall()

df = pd.DataFrame(
    data,
    columns=["Year", "Quarter", "Total_Policies", "Total_Insurance_Value"]
)

df["Year_Quarter"] = df["Year"].astype(str) + "-Q" + df["Quarter"].astype(str)
df = df[["Year_Quarter","Total_Policies","Total_Insurance_Value"]]
print(df.to_string(float_format='{:,.0f}'.format))

   Year_Quarter Total_Policies  Total_Insurance_Value
0       2020-Q2         556044            101,196,498
1       2020-Q3        1062852            268,485,228
2       2020-Q4         745878            512,939,799
3       2021-Q1         954345            618,887,106
4       2021-Q2        1091964            885,196,266
5       2021-Q3        1124580          1,027,166,487
6       2021-Q4        1578957          1,966,260,255
7       2022-Q1        1852725          2,662,241,319
8       2022-Q2        1892232          2,571,038,532
9       2022-Q3        2419362          3,164,018,670
10      2022-Q4        3106029          4,319,231,772
11      2023-Q1        2769441          4,226,330,175
12      2023-Q2        2681427          4,042,057,563
13      2023-Q3        3030576          4,335,628,251
14      2023-Q4        3477117          5,565,802,185
15      2024-Q1        3821283          5,795,767,413
16      2024-Q2        3315075          5,278,821,852
17      2024-Q3        3640887          5,823,796,923
18      2024-Q4        4426287          6,881,868,858

In [84]:
import plotly.express as px

fig = px.line(
    df,
    x="Year_Quarter",
    y="Total_Insurance_Value",
    markers=True,
    title="Insurance Value Growth by Quarter",
    line_shape="spline",
    color_discrete_sequence=["#2E86AB"]
)

fig.update_layout(
    title_x=0.5,
    template="plotly_white",
    width=950,
    height=500,
    xaxis_tickangle=-45,
    plot_bgcolor="#F8F9FA",
    paper_bgcolor="#FFFFFF",
    font=dict(size=14)
)

fig.update_traces(
    marker=dict(size=9),
    line=dict(width=2),
    text=df["Total_Insurance_Value"],
    textposition="top center"
)

fig.update_xaxes(showgrid=True, gridcolor="lightgray")
fig.update_yaxes(showgrid=True, gridcolor="lightgray")

fig.show()

# 4. Transaction Analysis for Market Expansion

# Query:1.Top Districts by Transaction Value

In [5]:
query = """
SELECT 
    State,
    District,
    SUM(Transaction_amount) AS Total_Transaction_Value
FROM map_transaction
GROUP BY State, District
ORDER BY Total_Transaction_Value DESC
LIMIT 10;
"""

cursor.execute(query)
data = cursor.fetchall()

df = pd.DataFrame(data, columns=["State","District","Total_Transaction_Value"])
print(df.to_string(float_format='{:,.0f}'.format))

            State            District  Total_Transaction_Value
0       karnataka     bengaluru urban       79,751,366,592,766
1       telangana           hyderabad       47,627,748,047,991
2     maharashtra                pune       38,920,871,095,833
3       rajasthan              jaipur       31,416,366,065,857
4       telangana          rangareddy       28,620,561,721,622
5       telangana  medchal malkajgiri       23,035,511,085,314
6  andhra-pradesh       visakhapatnam       16,794,272,370,317
7  andhra-pradesh              guntur       12,698,106,886,053
8  andhra-pradesh             krishna       12,571,425,463,236
9           bihar               patna       12,443,048,358,998

In [6]:
import plotly.express as px

fig = px.bar(
    df,
    x="District",
    y="Total_Transaction_Value",
    color="State",
    title="Top Districts by Transaction Value",
    text="Total_Transaction_Value",
    color_discrete_sequence=px.colors.qualitative.Set2
)

fig.update_layout(
    title_x=0.5,
    template="plotly_white",
    width=1000,
    height=550,
    xaxis_title="District",
    yaxis_title="Total Transaction Value",
    xaxis_tickangle=-45,
    bargap=0.25,
    plot_bgcolor="#F8F9FA",
    paper_bgcolor="#FFFFFF"
)

fig.update_traces(textposition="outside")

fig.show()

# Query.2:Lowest Performing Districts

In [7]:
query = """
SELECT 
    State,
    District,
    SUM(Transaction_amount) AS Total_Transaction_Value
FROM map_transaction
GROUP BY State, District
ORDER BY Total_Transaction_Value ASC
LIMIT 10;
"""

cursor.execute(query)
data = cursor.fetchall()

df = pd.DataFrame(data, columns=["State","District","Total_Transaction_Value"])
print(df.to_string(float_format='{:,.0f}'.format))

       State                  District  Total_Transaction_Value
0   nagaland                   niuland               10,979,804
1   nagaland                  tseminyu              213,012,352
2    mizoram                  khawzawl              239,938,976
3    mizoram                 hnahthial              297,014,264
4   nagaland                  shamator              341,888,800
5  meghalaya  eastern west khasi hills              511,692,404
6   nagaland                    noklak              570,676,368
7    manipur                  pherzawl              677,577,599
8    mizoram                   saitual              820,427,128
9    mizoram                     siaha            1,397,974,380

In [8]:
import plotly.express as px

fig = px.bar(
    df,
    y="District",
    x="Total_Transaction_Value",
    color="State",
    orientation="h",
    title="Lowest Performing Districts by Transaction Value",
    text="Total_Transaction_Value",
    color_discrete_sequence=px.colors.qualitative.Pastel
)

fig.update_layout(
    title_x=0.5,
    template="plotly_white",
    width=1000,
    height=550,
    xaxis_title="Total Transaction Value",
    yaxis_title="District",
    bargap=0.25,
    plot_bgcolor="#F8F9FA",
    paper_bgcolor="#FFFFFF"
)

fig.update_traces(textposition="outside")

fig.show()

# Query 3 Quarterly transaction growth trend

In [9]:
query = """
SELECT 
    Year,
    Quarter,
    SUM(Transaction_amount) AS Total_Transaction_Value
FROM aggregated_transaction
GROUP BY Year, Quarter
ORDER BY Year, Quarter;
"""

cursor.execute(query)
data = cursor.fetchall()

df = pd.DataFrame(
    data,
    columns=["Year","Quarter","Total_Transaction_Value"]
)
df["Year_Quarter"] = df["Year"].astype(str) + "-Q" + df["Quarter"].astype(str)
df = df[["Year_Quarter","Total_Transaction_Value"]]
print(df.to_string(float_format='{:,.0f}'.format))

   Year_Quarter  Total_Transaction_Value
0       2018-Q1          859,167,155,086
1       2018-Q2        1,521,871,058,336
2       2018-Q3        2,375,507,528,075
3       2018-Q4        3,358,681,240,571
4       2019-Q1        4,950,106,810,554
5       2019-Q2        6,771,070,185,462
6       2019-Q3        8,362,794,955,802
7       2019-Q4       11,299,468,714,127
8       2020-Q1       13,485,562,389,022
9       2020-Q2       13,230,725,539,863
10      2020-Q3       19,510,264,981,823
11      2020-Q4       26,979,256,979,597
12      2021-Q1       31,421,217,292,478
13      2021-Q2       37,382,329,833,084
14      2021-Q3       46,083,480,439,843
15      2021-Q4       58,106,470,870,428
16      2022-Q1       66,198,152,397,662
17      2022-Q2       77,520,932,442,595
18      2022-Q3       83,038,137,124,385
19      2022-Q4       94,574,442,589,884
20      2023-Q1      102,569,790,077,535
21      2023-Q2      114,592,471,458,700
22      2023-Q3      120,060,667,876,870
23      2023-Q4      135,236,137,582,500
24      2024-Q1      147,292,169,448,460
25      2024-Q2      159,101,754,629,655
26      2024-Q3      161,734,838,151,550
27      2024-Q4      179,994,004,422,985

In [11]:
import plotly.express as px

fig = px.line(
    df,
    x="Year_Quarter",
    y="Total_Transaction_Value",
    markers=True,
    title="Quarterly Transaction Growth Trend",
    line_shape="spline",  # smooth curve
    color_discrete_sequence=["#1f77b4"]
)

fig.update_layout(
    title_x=0.5,
    template="plotly_white",
    width=950,
    height=500,
    xaxis_title="Year & Quarter",
    yaxis_title="Total Transaction Value",
    xaxis_tickangle=-45,
    plot_bgcolor="#F8F9FA",
    paper_bgcolor="#FFFFFF",
    font=dict(size=14)
)

fig.update_traces(
    marker=dict(size=6),
    line=dict(width=3),
    text=df["Total_Transaction_Value"],
    textposition="top center"
)

fig.update_xaxes(showgrid=True, gridcolor="lightgray")
fig.update_yaxes(showgrid=True, gridcolor="lightgray")

fig.show()

# Query 4: Average Transaction Value per District

In [13]:
query = """
SELECT 
    State,
    District,
    SUM(Transaction_amount) / SUM(Transaction_count) AS Avg_Transaction_Value
FROM map_transaction
GROUP BY State, District
ORDER BY Avg_Transaction_Value DESC
LIMIT 10;
"""

cursor.execute(query)
data = cursor.fetchall()

df = pd.DataFrame(data, columns=["State","District","Avg_Transaction_Value"])

print(df.to_string(float_format='{:,.0f}'.format))

               State                District  Avg_Transaction_Value
0  arunachal-pradesh                shi yomi                  4,252
1            mizoram                   saiha                  3,557
2            manipur              tengnoupal                  3,282
3            manipur                 kamjong                  3,077
4            manipur                  ukhrul                  2,954
5            manipur           churachandpur                  2,906
6          meghalaya  south west khasi hills                  2,899
7           nagaland                    phek                  2,894
8           nagaland                tuensang                  2,880
9            mizoram                champhai                  2,836

In [19]:
import plotly.express as px

fig = px.bar(
    df,
    x="Avg_Transaction_Value",
    y="District",
    color="State",
    orientation="h",
    title="Top Districts by Average Transaction Value",
    
    color_discrete_sequence=px.colors.qualitative.Set2
)

fig.update_layout(
    title_x=0.5,
    template="plotly_white",
    width=1000,
    height=550,
    bargap=0.25,
    plot_bgcolor="#F8F9FA",
    paper_bgcolor="#FFFFFF",
   
)



fig.show()

Small districts often show higher averages because:

They may have low transaction count
But some transactions are high value
So the average becomes large
This insight actually means:

These districts have high-value transactions
But low volume
PhonePe could target high-income users or merchants there

So it’s still a valid business insight.

# Query: 5.High Transaction Count but Lower Value Districts

In [21]:
query = """
SELECT 
    State,
    District,
    SUM(Transaction_count) AS Total_Transactions,
    SUM(Transaction_amount) AS Total_Transaction_Value,
    SUM(Transaction_amount)/SUM(Transaction_count) AS Avg_Transaction_Value
FROM map_transaction
GROUP BY State, District
ORDER BY Total_Transactions DESC
LIMIT 10;
"""

cursor.execute(query)
data = cursor.fetchall()

df = pd.DataFrame(data, columns=[
    "State",
    "District",
    "Total_Transactions",
    "Total_Transaction_Value",
    "Avg_Transaction_Value"
])

print(df.to_string(float_format='{:,.0f}'.format))

            State            District Total_Transactions  Total_Transaction_Value  Avg_Transaction_Value
0       karnataka     bengaluru urban        68432535384       79,751,366,592,766                  1,165
1     maharashtra                pune        37476214176       38,920,871,095,833                  1,039
2       telangana           hyderabad        30805494664       47,627,748,047,991                  1,546
3       rajasthan              jaipur        21587481624       31,416,366,065,857                  1,455
4       telangana          rangareddy        20153660480       28,620,561,721,622                  1,420
5       telangana  medchal malkajgiri        16429287600       23,035,511,085,314                  1,402
6  andhra-pradesh       visakhapatnam        10303008764       16,794,272,370,317                  1,630
7          odisha             khordha         9790986304       11,968,588,285,478                  1,222
8         haryana            gurugram         9595264992        9,598,188,689,400                  1,000
9     maharashtra     mumbai suburban         9586801488       11,595,650,712,782                  1,210

In [22]:
import plotly.express as px

fig = px.bar(
    df,
    x="Total_Transactions",
    y="District",
    color="State",
    orientation="h",
    title="Top Districts by Transaction Activity",
    color_discrete_sequence=px.colors.qualitative.Set2
)

fig.update_layout(
    title_x=0.5,
    template="plotly_white",
    width=1000,
    height=550,
    xaxis_title="Total Transactions",
    yaxis_title="District",
    bargap=0.25,
    plot_bgcolor="#F8F9FA",
    paper_bgcolor="#FFFFFF",
    font=dict(size=14)
)

fig.show()

Query 4 finds luxury spending areas.
Query 5 finds high usage areas.
Query 4 → High-value markets
Query 5 → High-usage markets

# 5. User Engagement and Growth Strategy

# Query 1 — States with Highest User Engagement

In [23]:
query = """
SELECT 
    State,
    SUM(App_opens) / SUM(Registered_user) AS Engagement_Ratio
FROM map_users
GROUP BY State
ORDER BY Engagement_Ratio DESC
LIMIT 10;
"""

cursor.execute(query)
data = cursor.fetchall()

df = pd.DataFrame(data, columns=["State","Engagement_Ratio"])

print(df)

                       State Engagement_Ratio
0                  meghalaya         174.3572
1          arunachal-pradesh         138.8535
2                    mizoram         136.5701
3                     ladakh         129.4866
4  andaman-&-nicobar-islands          92.2914
5                  rajasthan          87.2793
6                      assam          84.3733
7             madhya-pradesh          84.3670
8               chhattisgarh          78.6445
9                   nagaland          76.1757

In [26]:
import plotly.express as px

fig = px.bar(
    df,
    x="State",
    y="Engagement_Ratio",
    title="States with Highest User Engagement",
    color="State",
    color_discrete_sequence=px.colors.qualitative.Bold
)

fig.update_layout(
    title_x=0.5,
    template="plotly_white",
    width=950,
    height=600,
    xaxis_tickangle=-45,
    bargap=0.25,
    plot_bgcolor="#F8F9FA",
    paper_bgcolor="#FFFFFF",
    font=dict(size=14)
)

fig.show()

Small states like:

Meghalaya
Mizoram
Arunachal Pradesh

may have fewer users, but those users open the app very frequently.

So their engagement ratio becomes high.

# Query 2 — Pincode Areas with Highest User Concentration

In [27]:
query = """ 
SELECT 
    State,
    Pincode,
    SUM(Registered_user) AS Total_Users
FROM top_users_pincode
GROUP BY State, Pincode
ORDER BY Total_Users DESC
LIMIT 10""" 

cursor.execute(query)
data = cursor.fetchall()

df = pd.DataFrame(data, columns=["State","Pincode","Total_Users"])

print(df.to_string(float_format='{:,.0f}'.format))

           State  Pincode Total_Users
0  uttar-pradesh   201301    50630961
1          delhi   110059    42502707
2      karnataka   560068    39008181
3    maharashtra   421302    37098780
4      telangana   500072    35314137
5          delhi   110092    33617490
6        haryana   122001    33383619
7          delhi   110086    29248857
8        haryana   121004    29027367
9  uttar-pradesh   201009    28255980

In [28]:
import plotly.express as px

# convert pincode to string
df["Pincode"] = df["Pincode"].astype(str)

fig = px.bar(
    df,
    x="Total_Users",
    y="Pincode",
    color="State",
    orientation="h",
    title="Top Pincode Areas by Registered Users",
    color_discrete_sequence=px.colors.qualitative.Set2
)

fig.update_layout(
    title_x=0.5,
    template="plotly_white",
    width=1000,
    height=550,
    xaxis_title="Total Registered Users",
    yaxis_title="Pincode",
    bargap=0.25,
    plot_bgcolor="#F8F9FA",
    paper_bgcolor="#FFFFFF",
    font=dict(size=14)
)

fig.show()

# Query 3:Districts with Highest User Engagement

In [29]:
query = """
SELECT 
    State,
    District,
    SUM(App_opens) / SUM(Registered_user) AS Engagement_Ratio
FROM map_users
GROUP BY State, District
ORDER BY Engagement_Ratio DESC
LIMIT 10;
"""

cursor.execute(query)
data = cursor.fetchall()

df = pd.DataFrame(data, columns=["State","District","Engagement_Ratio"])

print(df)

                       State                  District Engagement_Ratio
0                  meghalaya    south west khasi hills        1783.1573
1          arunachal-pradesh             pakke kessang        1599.9285
2                   nagaland                    noklak        1544.0665
3                  meghalaya  eastern west khasi hills        1477.4165
4          arunachal-pradesh                  shi yomi        1137.4717
5                    manipur                  senapati        1060.4298
6          arunachal-pradesh                     kamle         991.0692
7            jammu-&-kashmir              muzaffarabad         784.4664
8                  rajasthan                     kekri         783.5641
9  andaman-&-nicobar-islands                  nicobars         731.9770

In [30]:
import plotly.express as px

fig = px.bar(
    df,
    x="Engagement_Ratio",
    y="District",
    color="State",
    orientation="h",
    title="Districts with Highest PhonePe User Engagement",
    color_discrete_sequence=px.colors.qualitative.Set2
)

fig.update_layout(
    title_x=0.5,
    template="plotly_white",
    width=1000,
    height=550,
    xaxis_title="Engagement Ratio",
    yaxis_title="District",
    bargap=0.25,
    plot_bgcolor="#F8F9FA",
    paper_bgcolor="#FFFFFF",
    font=dict(size=14)
)

fig.show()

# Query 4 — User Growth Trend by Year and Quarter

In [31]:
query = """ 
SELECT 
    Year,
    Quarter,
    SUM(Registered_user) AS Total_Users
FROM map_users
GROUP BY Year, Quarter
ORDER BY Year, Quarter
"""
cursor.execute(query)
data = cursor.fetchall()

df = pd.DataFrame(data, columns=["Year","Quarter","Total_Users"])

df["Year_Quarter"] = df["Year"].astype(str) + "-Q" + df["Quarter"].astype(str)

print(df.to_string(float_format='{:,.0f}'.format))

    Year  Quarter Total_Users Year_Quarter
0   2018        1   140632959      2018-Q1
1   2018        2   190944027      2018-Q2
2   2018        3   240031767      2018-Q3
3   2018        4   306784863      2018-Q4
4   2019        1   370296564      2019-Q1
5   2019        2   425422962      2019-Q2
6   2019        3   477879957      2019-Q3
7   2019        4   534835251      2019-Q4
8   2020        1   592723377      2020-Q1
9   2020        2   656986788      2020-Q2
10  2020        3   723506688      2020-Q3
11  2020        4   792811302      2020-Q4
12  2021        1   854953533      2021-Q1
13  2021        2   915771303      2021-Q2
14  2021        3   985061568      2021-Q3
15  2021        4  1053480786      2021-Q4
16  2022        1  1118851881      2022-Q1
17  2022        2  1180270146      2022-Q2
18  2022        3  1242970638      2022-Q3
19  2022        4  1301839659      2022-Q4
20  2023        1  1361654214      2023-Q1
21  2023        2  1417105170      2023-Q2
22  2023        3  1474298442      2023-Q3
23  2023        4  1528069965      2023-Q4
24  2024        1  1590248571      2024-Q1
25  2024        2  1650858684      2024-Q2
26  2024        3  1704030153      2024-Q3
27  2024        4  1760269356      2024-Q4

In [34]:
import plotly.express as px

fig = px.line(
    df,
    x="Year_Quarter",
    y="Total_Users",
    markers=True,
    title="User Growth Trend Over Time",
    line_shape="spline",
    color_discrete_sequence=["#2E86AB"]
)

fig.update_layout(
    title_x=0.5,
    template="plotly_white",
    width=950,
    height=500,
    xaxis_tickangle=-45,
    plot_bgcolor="#F8F9FA",
    paper_bgcolor="#FFFFFF",
    font=dict(size=14)
)

fig.update_traces(
    marker=dict(size=7),
    line=dict(width=3)
)

fig.update_xaxes(showgrid=True, gridcolor="lightgray")
fig.update_yaxes(showgrid=True, gridcolor="lightgray")

fig.show()

# Query:5.States with Low Engagement
 (High Users but Fewer App Opens)

Find states where:

Registered users are high
but App opens are relatively low

This means:

Users installed PhonePe but do not use it frequently.

These states are important targets for engagement campaigns.

In [35]:
query = """ 
SELECT 
    State,
    SUM(Registered_user) AS Total_Users,
    SUM(App_opens) AS Total_App_Opens,
    SUM(App_opens) / SUM(Registered_user) AS Engagement_Ratio
FROM map_users
GROUP BY State
ORDER BY Engagement_Ratio ASC
LIMIT 10""" 
cursor.execute(query)
data = cursor.fetchall()

df = pd.DataFrame(data, columns=[
    "State",
    "Total_Users",
    "Total_App_Opens",
    "Engagement_Ratio"
])

print(df.to_string(float_format='{:,.2f}'.format))

                                State Total_Users Total_App_Opens Engagement_Ratio
0                          chandigarh    38566767       516692460          13.3973
1                               delhi   973824285     14541318987          14.9322
2                          puducherry    31221444       533887245          17.1000
3                              kerala   614274225     11906002704          19.3822
4  dadra-&-nagar-haveli-&-daman-&-diu    30240585       623204709          20.6082
5                         west-bengal  1574893074     32831456481          20.8468
6                             haryana   918066303     24777378639          26.9887
7                              punjab   514296753     15426696468          29.9957
8                                 goa    52311858      1584987837          30.2988
9                               bihar  1338345846     40824777753          30.5039

In [38]:
import plotly.express as px

# Sort states by lowest engagement
df = df.sort_values(by="Engagement_Ratio", ascending=True)

fig = px.bar(
    df,
    x="State",
    y="Engagement_Ratio",
    color="State",
    title="States with Lowest User Engagement",
    color_discrete_sequence=px.colors.qualitative.Set2
)

fig.update_layout(
    title_x=0.5,
    template="plotly_white",
    width=950,
    height=600,
    xaxis_tickangle=-45,
    bargap=0.25,
    plot_bgcolor="#F8F9FA",
    paper_bgcolor="#FFFFFF",
    font=dict(size=14)
)

fig.show()